DROP TYPE IF EXISTS grocery; 
CREATE TYPE grocery AS ENUM(
    'Main',
    'Snack',
    'Lunch',
    'Breakfast'
);

-- DROP TABLE shopping_list;
CREATE TABLE IF NOT EXISTS shopping_list (
    -- id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    id SERIAL PRIMARY KEY,
    name TEXT NOT NULL,
    price decimal(10,2) NOT NULL,
    date_added TIMESTAMP DEFAULT now() NOT NULL,
    checked BOOLEAN DEFAULT false,
    category grocery NOT NULL
);

-- $ psql -U dunder_mifflin -d knex-practice -f ./sql-scripts/create.shopping-list.sql
